# Example configuration for GoBot
#
#
# Before running your bot, copy this to config.yaml and
# change it to suit your needs. If you don't do this, the
# bot will clone this itself and connect to PS! main, using
# these default settings.
#
# Note that strings need not be quoted in YAML, except the
# empty string -- represented as "" -- and numbers that
# should be interpreted as strings
#
#
# The nickname to use on PS!. Limited to 16 characters.
nick: example
#
# The password associated with the given nick. Leave as ""
# if the nick is unregistered.
# NOTE: LOGGING IN WITHOUT A PASSWORD DOES NOT WORK CURRENTLY
pass: ""
#
# The server to connect to. Note that this is not necessarily
# the link you use to connect through a browser. PS! main uses
# sim.smogon.com
server: sim.smogon.com
#
# The port that the given server uses. PS!' default port is
# 8000, but some servers don't use that, so ask your server's
# admin what port they use if in doubt.
port: "8000"
