# Example configuration for GoBot
#
#
# Before running your bot, copy this to config.yaml and
# change it to suit your needs. If you don't do this, the
# bot will clone this itself and connect to PS! main, using
# these default settings.
#
# Note that strings need not be quoted in YAML, except the
# empty string -- represented as "" -- and numbers that
# should be interpreted as strings
#
#
# The nickname to use on PS!. Limited to 16 characters.
nick: example
#
# The password associated with the given nick. Leave as ""
# if the nick is unregistered.
pass: ""
#
# The server to connect to. Note that this is not necessarily
# the link you use to connect through a browser. PS! main uses
# sim.smogon.com
server: sim.smogon.com
#
# The port that the given server uses. PS!' default port is
# 8000, but some servers don't use that, so ask your server's
# admin what port they use if in doubt.
port: "8000"
#
# The command character that determines what commands the bot
# should interpret as being for it. Should be a single
# non-alphanumeric symbol.
commandchar: "."
#
# The rooms the bot should join upon connecting to PS!. Each
# room should be represented in the form `name: 1` with their
# names in the id form (lower-case alphanumeric characters
# only).
rooms:
  techcode: 1
#
# The port that the bot should listen on for GitHub webhook
# POST requests. Should be a number, not a string. Note that
# GitHub webhooks should be sent to url:PORT/postreceive,
# where PORT is the port given here.
hookport: 8080
#
# This is the secret that you give on GitHub when setting up a
# webhook. Make sure all webhooks to the bot use the same secret
hooksecret: example
#
# The list of rooms that should be updated when a GitHub webhook
# is received
hookrooms:
  - example
  - anotherroom
